# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meaning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher'
  # Pods for meaning

end
